### ISSUE TITLE
[Question] How do i make an array accessible to QML via @QtSlot ?

### ISSUE THREAD

**Issue by bamarc** [filcuc/dqml#17]
Which data types are available? Is there something like a QList which i can use to convert my data?

**Comment by filcuc** [comment]
do you mean support for [QQmlListProperty](http://doc.qt.io/qt-5/qqmllistproperty.html) ? or something more simple like QVariantList? The latter could be added without too much work. The same cannot be said for QQmlListProperty

**Comment by bamarc** [comment]
Okay, thank you. I solved it by wrapping every Array in a QObject, which works great.
