### ISSUE TITLE
Problem with QVariant and QObject

### ISSUE THREAD

**Issue by JoeKays** [filcuc/dqml#18]
Hi,

it seems that wrapping a QObject inside a QVariant does not work properly. The void* inside the QVariant for me points to a wrong address.
The following code prints e.g.: '55AF7A0C72E0 7FD2A2F15680', which are not the same addresses.

```
SomeQObject q = new SomeQObject();
QVariant qv = new QVariant(q);
writeln(qv.voidPointer, " ", cast(void*)q);
```
Similiarly when I have a QSlot() that accepts a QVariant and call the Slot from qml with a QObject I receive 'null' in the slot.

Any ideas?

**Comment by filcuc** [comment]
QVariant::voidPointer return the address of the QVariant created in C++ not the pointer of the QObject inside the QVariant.

**Comment by filcuc** [comment]
Currently QVariant don't have a getter for obtaining the QObject* pointer inside it. The reason is that is very simple to make error with a garbage collected language like D. The QObject contained the QVariant could be owned from C++ for example or from Qml.

**Comment by filcuc** [comment]
Please explain your use case in order to find a better approach or workaround/solution

**Comment by JoeKays** [comment]
Ah, I get it. That's a bit misleading, though.
But it's indeed dangerous in garbage collected languages most of the time.

In my case however the QObject is a custom QObject I made with D and passed to the QML using a QtSignal() and the Connection { } component in qml. That means that the object is actually owned by the D code already.

For my use case this object contains info about the data that is shown in the qml user interface. When the item is selected, some operations on the data of the object should be done for which a reference to the object is required.
Do you have any idea how to achieve that, other than storing the objects in a map with some identifier? Because that's the only solution I can think of right now and that's ugly, because the data objects are not ordered and I would have to compute a random identifier to pass to the qml then.

**Comment by filcuc** [comment]
I would simply add a method in the QObject that you pass to qml  that in
turn call the object that process its data.

Il Lun 25 Mar 2019, 20:18 Sir Pilcrow <notifications@github.com> ha scritto:
