### ISSUE TITLE
Compile error with Qt6 in Fedora

### ISSUE THREAD

**Issue by Behkar** [filcuc/dqml#21]
TextBin Error:
https://pastebin.pl/view/058bb330

I have installed all modules and libraries of Qt 6 on my system

DMD Version:
DMD64 D Compiler v2.100.2

LDC version:
 based on DMD v2.100.1 and LLVM 14.0.3

**Comment by filcuc** [comment]
mh something weird it's going on did you build/link DOtherSide with different Qt versions? those errors are due to libDOtherSide being compiled with those symbols/functions (so they're found during compilation) but failed to find them when linking.

**Comment by Behkar** [comment]
I uninstalled Fedora from my system and reinstalled Fedora newer version (Fedora 37) with qt 6, it worked.
And I also tested it on Ubuntu 22.04 and OpenSuse Tumbleweed , it worked.
