### ISSUE TITLE
QVariant: Arrays or list

### ISSUE THREAD

**Issue by 9il** [filcuc/dqml#5]
Can you add support for arrays/lists before breaking changes please?

**Comment by filcuc** [comment]
do you mean QAbstractListModels? currently is still possible even without
them

2015-03-02 21:09 GMT+01:00 Ilya Yaroshenko notifications@github.com:

> Can you add support for arrays/lists before breaking changes please?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/filcuc/dqml/issues/5.

## 

Filippo Cucchetto

**Comment by 9il** [comment]
Yes

**Comment by filcuc** [comment]
Take a look at the left side of this diff
https://github.com/filcuc/DOtherSide/commit/de533129d21478912c67761260e87dd78bf5c16f?diff=split

Basically you create a QObject with:
- an array of QObjects
- a Count property of type int that return the array length
- add a get slot that return the i-th element
- add some functions for add/removing items in the array. Everytime you
  remove/add an element emit the countChanged signals
- in the qml bind the model property of a listView to you QObject count
  property (in this way you get n-th elements)
- in the delegate call your QObject get function with the delegate index

2015-03-02 21:29 GMT+01:00 Ilya Yaroshenko notifications@github.com:

> Yes
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/filcuc/dqml/issues/5#issuecomment-76811069.

## 

Filippo Cucchetto

**Comment by filcuc** [comment]
however i can  write an example before making breaking changes

**Comment by filcuc** [comment]
sorry i think that the D implementation lacks of QObject support in slots and signals. I'll push a fix as soon as possible with a working example

**Comment by 9il** [comment]
Breaking changes is not a problem. I need something to draw charts/plots with hardware acceleration. I hope it can be dqml. But without arrays/lists it is impossible now.

**Comment by filcuc** [comment]
yep i understand it

**Comment by filcuc** [comment]
This evening i didn't had the time to get completely with dub. In these
days i plan to delete the D code from the DOtherSide and continue the
development here.

However on the develop branch of the DOtherSide repo you should find an
implementation that support the QObject and an example with a list of items.

2015-03-02 21:40 GMT+01:00 Ilya Yaroshenko notifications@github.com:

> Breaking changes is not problem. I need something to draw charts/plots
> with hardware acceleration. I hope it can be dqml. But without arrays/lists
> it is impossible now.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/filcuc/dqml/issues/5#issuecomment-76815075.

## 

Filippo Cucchetto

**Comment by filcuc** [comment]
@9il  have you tried my changes?

**Comment by 9il** [comment]
Hi! I am a little bit miss-oriented. Is QML list implemented like D range of QObjects?

**Comment by filcuc** [comment]
No, you just expose to QML a QObject with a count property and a get slot.
Than QML invoke th get slot that returns a simple type (a double/int/ etc)

2015-03-05 14:01 GMT+01:00 Ilya Yaroshenko notifications@github.com:

> Hi! I am a little bit miss-oriented. Is QML list implemented like D range
> of QObjects?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/filcuc/dqml/issues/5#issuecomment-77359712.

## 

Filippo Cucchetto

**Comment by filcuc** [comment]
Basically the QObject is a Model/Container

2015-03-05 14:09 GMT+01:00 Filippo Cucchetto filippocucchetto@gmail.com:

> No, you just expose to QML a QObject with a count property and a get slot.
> Than QML invoke th get slot that returns a simple type (a double/int/ etc)
> 
> 2015-03-05 14:01 GMT+01:00 Ilya Yaroshenko notifications@github.com:
> 
> > Hi! I am a little bit miss-oriented. Is QML list implemented like D range
> > of QObjects?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/filcuc/dqml/issues/5#issuecomment-77359712.
> 
> ## 
> 
> Filippo Cucchetto

## 

Filippo Cucchetto
